pipek/web/views/sites.py
from flask import Blueprint, render_template, redirect, Response, request
import cv2
import datetime, time
import os, sys
import numpy as np
from threading import Thread

module = Blueprint("site", __name__, template_folder="templates")

camera = cv2.VideoCapture(0)

global capture, rec_frame, grey, switch, neg, face, rec, out
capture = 0
grey = 0
neg = 0
face = 0
switch = 1
rec = 0

# make shots directory to save pics
try:
    os.mkdir("./shots")
except OSError as error:
    pass

base_path = os.path.dirname(os.path.abspath(__file__))
# Load pretrained face detection model
print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.. Current working directory:", os.getcwd())
# Construct absolute paths for the model files
prototxt_path = os.path.join(base_path, "../views/deploy.prototxt.txt")
model_path = os.path.join(
    base_path, "../views/res10_300x300_ssd_iter_140000.caffemodel"
)

# Load the pretrained model
net = cv2.dnn.readNetFromCaffe(prototxt_path, model_path)


camera = cv2.VideoCapture(0)


def record(out):
    global rec_frame
    while rec:
        time.sleep(0.05)
        out.write(rec_frame)


def detect_face(frame):
    global net
    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(
        cv2.resize(frame, (300, 300)), 1.0, (300, 300), (104.0, 177.0, 123.0)
    )
    net.setInput(blob)
    detections = net.forward()
    confidence = detections[0, 0, 0, 2]

    if confidence < 0.5:
        return frame

    box = detections[0, 0, 0, 3:7] * np.array([w, h, w, h])
    (startX, startY, endX, endY) = box.astype("int")
    try:
        frame = frame[startY:endY, startX:endX]
        (h, w) = frame.shape[:2]
        r = 480 / float(h)
        dim = (int(w * r), 480)
        frame = cv2.resize(frame, dim)
    except Exception as e:
        pass
    return frame


def gen_frames():  # generate frame by frame from camera
    global out, capture, rec_frame
    while True:
        success, frame = camera.read()
        if success:
            if face:
                frame = detect_face(frame)
            if grey:
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            if neg:
                frame = cv2.bitwise_not(frame)
            if capture:
                capture = 0
                now = datetime.datetime.now()
                p = os.path.sep.join(
                    ["shots", "shot_{}.png".format(str(now).replace(":", ""))]
                )
                cv2.imwrite(p, frame)

            if rec:
                rec_frame = frame
                frame = cv2.putText(
                    cv2.flip(frame, 1),
                    "Recording...",
                    (0, 25),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1,
                    (0, 0, 255),
                    4,
                )
                frame = cv2.flip(frame, 1)

            try:
                ret, buffer = cv2.imencode(".jpg", cv2.flip(frame, 1))
                frame = buffer.tobytes()
                yield (
                    b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n"
                )
            except Exception as e:
                pass

        else:
            pass


@module.route("/")
def index():
    return render_template("index.html")


@module.route("/video_feed")
def video_feed():
    return Response(gen_frames(), mimetype="multipart/x-mixed-replace; boundary=frame")


@module.route("/requests", methods=["POST", "GET"])
def tasks():
    global switch, camera
    if request.method == "POST":
        if request.form.get("click") == "Capture":
            global capture
            capture = 1
        elif request.form.get("grey") == "Grey":
            global grey
            grey = not grey
        elif request.form.get("neg") == "Negative":
            global neg
            neg = not neg
        elif request.form.get("face") == "Face Only":
            global face
            face = not face
            if face:
                time.sleep(4)
        elif request.form.get("stop") == "Stop/Start":

            if switch == 1:
                switch = 0
                camera.release()
                cv2.destroyAllWindows()

            else:
                camera = cv2.VideoCapture(0)
                switch = 1
        elif request.form.get("rec") == "Start/Stop Recording":
            global rec, out
            rec = not rec
            if rec:
                now = datetime.datetime.now()
                fourcc = cv2.VideoWriter_fourcc(*"XVID")
                out = cv2.VideoWriter(
                    "vid_{}.avi".format(str(now).replace(":", "")),
                    fourcc,
                    20.0,
                    (640, 480),
                )
                # Start new thread for recording the video
                thread = Thread(
                    target=record,
                    args=[
                        out,
                    ],
                )
                thread.start()
            elif rec == False:
                out.release()

    elif request.method == "GET":
        return render_template("index.html")
    return render_template("index.html")


if __name__ == "__main__":
    camera.release()
    cv2.destroyAllWindows()


# def generate_frames():
#     while True:

#         ## read the camera frame
#         success, frame = camera.read()
#         if not success:
#             break
#         else:
#             ret, buffer = cv2.imencode(".jpg", frame)
#             frame = buffer.tobytes()

#         yield (b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n")


# @module.route("/")
# def index():
#     return render_template("index.html")


# @module.route("/video")
# def video():
#     return Response(
#         generate_frames(), mimetype="multipart/x-mixed-replace; boundary=frame"
#     )

pipek/web/templates/cam.html

<body>
<div class="container">
    <div class="row">
        <div class="col-lg-8  offset-lg-2">

			
            <h2 class="mt-5">CAMERA APP by Hemanth Nag</h2>
			<form method="post" action="{{ url_for('tasks') }}">
			<input type="submit" value="Stop/Start" name="stop" />
			<input type="submit" value="Capture" name="click"/>
			<input type="submit" value="Grey" name="grey" />
			<input type="submit" value="Negative" name="neg" />
			<input type="submit" value="Face Only" name="face" />
			<input type="submit" value="Start/Stop Recording" name="rec" />
			</form>
            <img src="{{ url_for('video_feed') }}" height="80%">
			<h3 style="font-family:courier;">Instructions:</h3>
			<ol style="font-family:courier;">
			<li>Stop/Start--Toggle between stop or start live streaming</li>
			<li>Capture--Take still-shot and save in the 'shots' directory</li>
			<li>Grey--Toggle between grayscale and RGB output</li>
			<li>Negative--Toggle between negative and RGB output</li>
			<li>Face Only--Shows just your face if present(Toggle on/off)</li> 
			<li>Start/Stop Recording--Toggle between starting and stopping video recording</li> </ol>	
			
        </div>
    </div>
</div>
</body>

pipek/web/templates/index.html
<!DOCTYPE html>
<html>



<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-8  offset-lg-2">


                <h2 class="mt-5">CAMERA APP by Hemanth Nag</h2>
                <form method="post" action="{{ url_for('site.tasks') }}">
                    <input type="submit" value="Stop/Start" name="stop" />
                    <input type="submit" value="Capture" name="click" />
                    <input type="submit" value="Grey" name="grey" />
                    <input type="submit" value="Negative" name="neg" />
                    <input type="submit" value="Face Only" name="face" />
                    <input type="submit" value="Start/Stop Recording" name="rec" />
                </form>
                <img src="{{ url_for('site.video_feed') }}" height="80%">
                <h3 style="font-family:courier;">Instructions:</h3>
                <ol style="font-family:courier;">
                    <li>Stop/Start--Toggle between stop or start live streaming</li>
                    <li>Capture--Take still-shot and save in the 'shots' directory</li>
                    <li>Grey--Toggle between grayscale and RGB output</li>
                    <li>Negative--Toggle between negative and RGB output</li>
                    <li>Face Only--Shows just your face if present(Toggle on/off)</li>
                    <li>Start/Stop Recording--Toggle between starting and stopping video recording</li>
                </ol>

            </div>
        </div>
    </div>
</body>



</html>